#ifndef GAME_STATES_H
#define GAME_STATES_H

typedef enum{
    STATE_INTRO,
    STATE_DOOR_LOCKED,
    STATE_CROUCH_DONE,
    STATE_INSIDE_HOUSE,
    STATE_KEY_BOX_PICKUP,
    STATE_NO_CLUTCH,
    STATE_CLUTCH_PICKUP,
    STATE_CAR_REPAIRED,
    STATE_COUNT
} GameState;

extern GameState currentState;

#endif